DONE/Controllers/ClienteController.cs
using DONE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using Excel = Microsoft.Office.Interop.Excel;
using System.IO;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Text;



namespace DONE.Controllers
{
    public class ClienteController : Controller
    {
        GVALORContext db = new GVALORContext();
        public ActionResult Carganomina()
        {
            var list = db.tcliente.ToList();
            list.Add(new tcliente { idcliente = 0, nombre = "[Seleccione un Cliente]" });
            list = list.OrderBy(c => c.nombre).ToList();
            ViewBag.idcliente = new SelectList(list, "idcliente", "nombre", "nombre");
            ViewBag.Error = "Debe seleccionar un cliente";
            return View();
        }
        public ActionResult Modal(int id, String mensaje, String titulo)
        {
            ViewBag.idcliente = new SelectList(db.tcliente, "idcliente", "nombre", "nombre");
            ViewBag.Error = "Debe seleccionar un cliente";
            ViewData["id"] = id;
            ViewData["mensaje"] = mensaje;
            ViewData["titulo"] = titulo;
            return View("carganomina");
        }
        public FileResult Download()
        {
            // Obtener contenido del archivo
            var ruta = Server.MapPath("~/Descargas/Formato_nomina.xlsx");
            return File(ruta, "application/vnd.ms-excel", "Formato_nomina.xlsx");
        }
        public JsonResult llenarListadoEmpleados()
        {

            int a = (int)(Session["id_cliente"]);
            int x = a;
            var lista = from c in db.templeado
                        where c.idcliente == x
                        select new
                        {
                            Codigo = c.idempleado,
                            Nombre = c.nombre + " " + c.apellidopaterno
                        };

            return Json(lista);

        }
        public ActionResult AsignarSueldosEditar(double porcentaje, int idempleado)
        {
            double valor = porcentaje / 100;
            
            var empleado = db.templeado.Find(idempleado);
            empleado.sueldo_sa=empleado.sueldototal*valor;
            empleado.sueldo_asimilado = empleado.sueldototal-(empleado.sueldototal * valor);

            return View();
            
        }
        public JsonResult EditarPorcentaje(List<ModelEmpleados> ListJson, double NuevoPorcentaje)
        {
            
            foreach (var item in ListJson)
            {
                var lista = from c in db.templeado
                            where c.idempleado == item.codigo
                            select c;
                foreach (templeado c in lista)
                {
                    c.porc_sa = NuevoPorcentaje;
                    AsignarSueldosEditar(NuevoPorcentaje,c.idempleado);
                    
                }
                try
                {
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }

            }

            return Json(ListJson);
        }
        public ActionResult Lista_Empleados()
        {
            int a = (int)(Session["id_cliente"]);
            int x = a;
            List<templeado> empleado = new List<templeado>();


            var lista_empleados = from c in db.templeado
                                  where c.idcliente == x
                                  select new
                                  {
                                      c.nombre,
                                      c.idempleado,
                                      c.apellidomaterno,
                                      c.apellidopaterno,
                                      c.sueldo_sindicato,
                                      c.sueldo_sa,
                                      c.sueldo_asimilado,
                                      c.porc_sa
                                  };

            foreach (var item in lista_empleados)
            {
                templeado auxi = new templeado();
                auxi.nombre = item.nombre + " " + item.apellidopaterno + " " + item.apellidomaterno;
                auxi.idempleado = item.idempleado;
                auxi.sueldo_asimilado = item.sueldo_asimilado;
                auxi.sueldo_sa = item.sueldo_sa;
                auxi.sueldo_sindicato = item.sueldo_sindicato;
                auxi.porc_sa = item.porc_sa;
                empleado.Add(auxi);

            }

            ViewBag.lista_empleados = empleado;
            return View();
        }
        [HttpPost]
        public ActionResult Import(HttpPostedFileBase excelfile, int idcliente)
        {

            Session["id_cliente"] = idcliente;
            string nombre_cliente = null;

            if (excelfile == null || excelfile.ContentLength == 0)
            {
                ViewBag.Error = "Debe Seleccionar un archivo <br>";
                return RedirectToAction("Modal", new { id = 1, mensaje = "Todos los campos son obligatorios", titulo = "¡Error!" });
            }
            else
            {
                ViewBag.idcliente = new SelectList(db.tcliente, "idcliente", "nombre", "nombre");
                if (excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx"))
                {
                    var lista = from c in db.tcliente
                                where c.idcliente == idcliente
                                select c;
                    foreach (tcliente c in lista)
                    {
                        nombre_cliente = c.nombre;
                    }

                    string nombreArchivo = nombre_cliente + "-" + excelfile.FileName;
                    string path = Server.MapPath("~/Nominas/" + nombre_cliente + "-" + excelfile.FileName);
                    if (System.IO.File.Exists(path))
                        System.IO.File.Delete(path);

                    excelfile.SaveAs(path);

                    String[] separa;
                    String nombreEnviar;
                    separa = nombreArchivo.Split('.');

                    nombreEnviar = separa[0];

                    int retorna;
                  
                    retorna=db.sp_lee_excel_pru(idcliente.ToString(), nombreEnviar);


                    if (retorna == 0)
                    {

                        return RedirectToAction("Modal", new { id = 1, mensaje = "Compruebe que el archivo que intenta cargar tiene la estructura correcta.", titulo = "¡Carga de nómina no completada!" });
                    }
                    else
                    {

                        AsignarSueldos();
                        return RedirectToAction("Modal", new { id = 2, titulo = "¡Carga de nómina completada con éxito!" });

                    }
                }
                return View();
            }
        }
      
        public JsonResult ValidarExtension(string nombre)
        {
            JsonResponse Respuesta = new JsonResponse();

            if (nombre.IndexOf(".xls") < 0 || nombre.IndexOf(".xlsx") < 0)
            {
                Respuesta.bandera = false;
                Respuesta.texto = "Solo archivos excel! (.xls/.xlsx)";
            }
            else
            {
                Respuesta.bandera = true;
            }

            return Json(Respuesta);
        }
        public ActionResult AsignarSueldos()
        {
            double valor;
            int a = (int)(Session["id_cliente"]);
            int x = a;
            
            var lista_empleados = from c in db.templeado
                                  where c.idcliente == x
                                  select new
                                  {
                                      c.idempleado,
                                      c.sueldo_asimilado,
                                      c.sueldo_sindicato,
                                      c.sueldo_sa,
                                      c.sueldototal,
                                      c.porc_sa
                                  };

            foreach (var item in lista_empleados)
            {
                var empleado = db.templeado.Find(item.idempleado);
                valor = (double)item.porc_sa / 100;
                empleado.sueldo_sa = empleado.sueldototal * valor;
                empleado.sueldo_asimilado = empleado.sueldototal - (empleado.sueldototal * valor);
               

            }
            try
            {
                db.SaveChanges();
                
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            return View();
        }
    }
}

DONE/Views/Cliente/Carganomina.cshtml
@model DONE.Models.tcliente

@{
    ViewBag.Title = "Carga Nomina";

}

@using (Html.BeginForm("Import", "Cliente", FormMethod.Post, new { enctype = "multipart/form-data", @id = "nominaForm" }))
{

    <div class="row">
        <div class="lista row">
            <ul>
                <li class="col-lg-4 col-md-12 col-sm-12"><a class="active">1.Carga de nómina</a></li>
                <li class="col-lg-4 col-md-12 col-sm-12"><a>2.Segmentación de empleados</a></li>
                <li class="col-lg-4 col-md-12 col-sm-12"><a>3.Asignación de salario</a></li>
            </ul>
        </div>


        <div class="row-fluid">
            <div class="col-md-6 col-sm-6 col-xs-6">
                @Html.DropDownList("idcliente", null, htmlAttributes: new { })
                @Html.ValidationMessageFor(model => model.idcliente, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-offset-2 col-md-4 descargar col-sm-6  col-xs-6">
                <a id="download" class="btn btn-primary a-dowload-file " href="#" onclick="downloadFile();return false;">DESCARGAR ARCHIVO DE EJEMPLO</a>
            </div>
        </div>


        <div class="row-fluid">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <input id="excelfile" name="excelfile" type="file" style="display:none" />
                <input id="nombre_archivo" class="input-file-name" readonly type="text" name="name" placeholder="Seleccionar archivo..." />
                <br />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
                <input id="btn_submit" class="btn btn-primary btn-block cargar btn-load-file" type="submit" name="submit" value="CARGAR" />
            </div>
        </div>
        <input id="tipoModal" type="hidden" name="name" value="@ViewData["id"]" />
        <div id="modalMensaje" class="modal fade ">
            <div class="modal-dialog">
                <div class="modal-content  modal-lg">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 id="titulo_modal" class="modal-title">@ViewData["titulo"]</h4>
                    </div>
                    <div class="modal-body">

                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p id="mensaje_error">@ViewData["mensaje"]</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4 col-md-offset-4 col-sm-12 col-xs-12">
                                <button type="button" class="btn btn-primary aceptar_modal" data-dismiss="modal">ACEPTAR</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input id="tipoModal" type="hidden" name="name" value="@ViewData["id"]" />
        <div id="modalSeguir" class="modal fade ">
            <div class="modal-dialog">
                <div class="modal-content  modal-lg">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 id="titulo_modal" class="modal-title">@ViewData["titulo"]</h4>
                    </div>
                    <div class="modal-body">

                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <p id="mensaje_error">@ViewData["mensaje"]</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4 col-md-offset-4 col-sm-12 col-xs-12">
                                <button type="button" class="btn btn-primary aceptar_modal" onclick="PasarListaEmpleados(); return false">ACEPTAR</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>

}

@section Scripts {


    <script type="text/javascript">

        $(function () {
            var archivo = null;
            var files = null;

            $("#nombre_archivo").click(function () {
                $("#excelfile").click();
            });

            var tipo = $("#tipoModal").val();
            if( tipo == 1 ){
                $("#modalMensaje").modal('show');
            }
            else if( tipo == 2 ){
                $("#modalSeguir").modal('show');
            }

            $("#excelfile").change(function (e) {
                archivo = e.target.files[0].name;

                $.ajax({
                    type: "POST",
                    url: "/gvalor/Cliente/ValidarExtension",
                    data: {
                        nombre: archivo
                    },
                    dataType: "json",
                    success: function (data) {

                        if (data.bandera == false)
                        {
                            $("#titulo_modal").text("¡Carga de nómina no completada!");
                            $("#modalMensaje").modal('show');
                            $("#mensaje_error").text("Compruebe que el archivo que intenta cargar tiene la estructura correcta.");

                        } else {
                            $("#nombre_archivo").val(archivo);
                            files = e.target.files[0];
                        }

                    },
                    failure: function (response) { },
                    error: function (error) { }
                });

            });


        });
        function downloadFile() {
            window.location = "@Url.Action("Download", "Cliente")";
        }
        function PasarListaEmpleados() {
            window.location = "@Url.Action("Lista_Empleados", "Cliente")";
        }


    </script>

}

DONE/Views/Cliente/Lista_Empleados.cshtml
@model DONE.Models.templeado
@{

}

<link href="~/Content/css/select2.css" rel="stylesheet" />

<div class="row">
    <div class="lista row">
        <ul>
            <li class="col-lg-4 col-md-12 col-sm-12"><a>1.Carga de nómina</a></li>
            <li class="col-lg-4 col-md-12 col-sm-12"><a>2.Segmentación de empleados</a></li>
            <li class="col-lg-4 col-md-12 col-sm-12"><a class="active">3.Asignación de salario</a></li>
        </ul>
    </div>


    <div class="row">
        <div class="col-lg-8 col-md-8 hidden-sm hidden-xs"></div>
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            <button class="btn btn-primary btn-block" id="editar">MODIFICAR % DE SA</button>
        </div>
    </div>


    
    <div class="container">
        <div class="row">
            <div class="table-responsive">
                <table class="table-listaEmpleados">
                    <thead>
                        <tr class="tr-listaEmpleados">
                            <th class="th-listaEmpleados">NOMBRE</th>
                            <th class="th-listaEmpleados">SUELDO SA</th>
                            <th class="th-listaEmpleados">SUELDO ASIMILADO</th>
                            <th class="th-listaEmpleados">SUELDO SINDICATO</th>
                            <th class="th-listaEmpleados">% SA</th>

                        </tr>
                    </thead>
                    <tbody id="myTable">
                        @for (int i = 0; i < ViewBag.lista_empleados.Count; i++)
                        {
                            <tr class="tr-listaEmpleados">
                                <td style="text-align:left" class="td-listaEmpleados">
                                    <p>@ViewBag.lista_empleados[i].nombre</p>
                                </td>

                                <td style="text-align:left">
                                    @if (@ViewBag.lista_empleados[i].sueldo_sa != null|| @ViewBag.lista_empleados[i].sueldo_sa != 0)
                                    {
                                        <p>@ViewBag.lista_empleados[i].sueldo_sa</p>

                                    }
                                    else
                                    {
                                        <p>-</p>
                                    }

                                </td>
                                <td style="text-align:left" class="td-listaEmpleados">

                                    @if (@ViewBag.lista_empleados[i].sueldo_sindicato != null|| @ViewBag.lista_empleados[i].sueldo_sindicato != 0)
                                    {
                                        <p>@ViewBag.lista_empleados[i].sueldo_sindicato</p>

                                    }
                                    else
                                    {
                                        <p>-</p>
                                    }

                                </td>
                                <td style="text-align:left" class="td-listaEmpleados">
                                    @if (@ViewBag.lista_empleados[i].sueldo_asimilado != null|| @ViewBag.lista_empleados[i].sueldo_sindicato != 0)
                                    {
                                        <p>@ViewBag.lista_empleados[i].sueldo_asimilado</p>

                                    }
                                    else
                                    {
                                        <p>-</p>
                                    }

                                </td>
                                <td style="text-align:left" class="td-listaEmpleados">
                                     <p>@ViewBag.lista_empleados[i].porc_sa</p>
                                </td>

                        </tr>
                    }
                    </tbody>

                </table>
            </div>
            <div class="paginarListado col-md-12 text-center">
                <ul class="pagination pagination-lg pager" id="myPager"></ul>
            </div>
        </div>
    </div>

</div>



<input id="tipoModal" type="hidden" name="name" value="" />
<div id="modalMensaje" class="modal fade " data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content  modal-lg">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 id="titulo_modal" class="modal-title">MODIFICAR % DE SA</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <select name="origen[]" id="origen" class="js-example-basic-multiple form-control select2" multiple="multiple"></select>
                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <div id="nuevo_sa" class="form-horizontal">
                            <div class="control-group form-inline">
                                <label for="editar_sa" class="sa_editar control-label col-xs-5">Nuevo % de SA</label>
                                <div class="controls col-xs-6">
                                    <input required="required"   step="0.01" class="form-control" id="editar_sa" type="number" aria-describedby="basic-addon1">
                                   
                                </div>
                            </div>
                        </div>
                    </div>      
                </div>
                <div class="row">
                    <div class="row col-md-3 col-md-offset-3 col-sm-12 col-xs-12">
                        <input type="button" id="aceptarModal" class="btn btn-primary aceptar" value="ACEPTAR" disabled data-dismiss="modal" />
                    </div>
                    <div class="row col-md-3 col-sm-12 col-xs-12">
                        <button type="button" id="cancelarModal" class="btn btn-primary cancelar" data-dismiss="modal">CANCELAR</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>




@section Scripts {
@Scripts.Render("~/Scripts/select2.js")
    <script type="text/javascript">
        var listado = [];
        var listado_Seleccionados = [];
        var sueldoEditado;


        $(document).ready(function () {
            $(".js-example-basic-multiple").select2({
                placeholder: "Seleccionar Empleado",
                allowClear: true,
            });

            $("#editar").click(function () {
               
                $("#modalMensaje").modal('show');
            });

            $('#myTable').pageMe({ pagerSelector: '#myPager', showPrevNext: true, hidePageNumbers: false, perPage: 50 });

            $("#origen").change(function () {
                if ($("#editar_sa").val().length > 0 && $('#origen option:selected').length>0) {
                    $('#aceptarModal').attr('disabled',false);
                }
                else
                {
                    $('#aceptarModal').attr('disabled', true);
                }
            });

            $("#editar_sa").keyup(function () {
                if ($("#editar_sa").val() > 0 && $('#origen option:selected').length > 0 && $("#editar_sa").val() < 100 ) {
                    $('#aceptarModal').attr('disabled', false);
                }
                else {
                    $('#aceptarModal').attr('disabled', true);
                }
            });

            $(function () {
            $("#aceptarModal").click(function () {
                sueldoEditado = $("#editar_sa").val().replace(/\./g, ',');
             

                $.each($('#origen option:selected'), function (index, item) {

                    console.log("id",item.value);
                    listado_Seleccionados.push({
                        "codigo": item.value,
                        "nombre": item.text
                    });
                   
                  
                });

               
                if (listado_Seleccionados.length <= 0 || sueldoEditado.length<=0) {
                    
                } else {
                 
                        $.ajax({
                            url: "/gvalor/Cliente/EditarPorcentaje",
                        type: "POST",
                        data: JSON.stringify({
                            ListJson: listado_Seleccionados,
                            NuevoPorcentaje: sueldoEditado
                        }),
                        contentType: "application/json",
                        dataType: "json",
                        success: function (result) {
                            $("#origen").find('option:selected').remove().end();
                            $("#editar_sa").val("");
                            location.reload();
                           
                        }
                        });

                        
                }

            });

           });

            $.ajax({
                type: "POST",
                url: "/gvalor/Cliente/llenarListadoEmpleados",
                data: "{}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (msg) {
                    listado = msg;

                    $(msg).each(function () {
                        var option = $(document.createElement('option'));
                        option.text(this.Nombre);
                        option.val(this.Codigo);
                        $("#origen").append(option);
                    });
                },
                error: function (msg) {
                    $("#dvAlerta > span").text("Error al llenar el combo");
                }
            });


        });

        $.fn.pageMe = function (opts) {
            var $this = this,
                defaults = {
                    perPage: 10,
                    showPrevNext: false,
                    numbersPerPage: 10,
                    hidePageNumbers: false,
                    showFirstLast: true
                },
                settings = $.extend(defaults, opts);

            var listElement = $this;
            var perPage = settings.perPage;
            var children = listElement.children();
            var pager = $('.pager');

            if (typeof settings.childSelector != "undefined") {
                children = listElement.find(settings.childSelector);
            }

            if (typeof settings.pagerSelector != "undefined") {
                pager = $(settings.pagerSelector);
            }

            var numItems = children.length;
            var numPages = Math.ceil(numItems / perPage);

            pager.data("curr", 0);

            if (settings.showPrevNext) {
                $('<li><a href="#" class="prev_link"></a></li>').appendTo(pager);
            }

            var curr = 0;
            while (numPages > curr && (settings.hidePageNumbers == false)) {
                $('<li><a href="#" class="page_link">' + (curr + 1) + '</a></li>').appendTo(pager);
                curr++;
            }

            if (settings.showPrevNext) {
                $('<li><a href="#" class="next_link"></a></li>').appendTo(pager);
            }

            pager.find('.page_link:first').addClass('active');
            pager.find('.prev_link').hide();
            if (numPages <= 1) {
                pager.find('.next_link').hide();
            }
            pager.children().eq(1).addClass("active");

            children.hide();
            children.slice(0, perPage).show();

            pager.find('li .page_link').click(function () {
                var clickedPage = $(this).html().valueOf() - 1;
                goTo(clickedPage, perPage);
                return false;
            });
            pager.find('li .prev_link').click(function () {
                previous();
                return false;
            });
            pager.find('li .next_link').click(function () {
                next();
                return false;
            });

            function previous() {
                var goToPage = parseInt(pager.data("curr")) - 1;
                goTo(goToPage);
            }

            function next() {
                goToPage = parseInt(pager.data("curr")) + 1;
                goTo(goToPage);
            }

            function goTo(page) {
                var startAt = page * perPage,
                    endOn = startAt + perPage;

                children.css('display', 'none').slice(startAt, endOn).show();

                if (page >= 1) {
                    pager.find('.prev_link').show();
                }
                else {
                    pager.find('.prev_link').hide();
                }

                if (page < (numPages - 1)) {
                    pager.find('.next_link').show();
                }
                else {
                    pager.find('.next_link').hide();
                }

                pager.data("curr", page);
                pager.children().removeClass("active");
                pager.children().eq(page + 1).addClass("active");

            }
        };

      


    </script>
}

DONE/Views/Cliente/editar.cshtml
<link href="~/Content/css/select2.css" rel="stylesheet" />


<input id="tipoModal" type="hidden" name="name" value="" />
<div id="modalMensaje" class="modal fade ">
    <div class="modal-dialog">
        <div class="modal-content  modal-lg">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 id="titulo_modal" class="modal-title">MODIFICAR % DE SA</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <select name="origen[]" id="origen" class="js-example-basic-multiple form-control select2" multiple="multiple"></select>
                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <div id="nuevo_sa" class="form-horizontal">
                            <div class="control-group form-inline">
                                <label for="editar_sa" class="sa_editar control-label col-xs-5">Nuevo % de SA</label>
                                <div class="controls col-xs-6">
                                    <input class="form-control" id="editar_sa" type="text">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row col-md-6 col-sm-12 col-xs-12">
                        <button type="button" class="btn btn-primary aceptar" data-dismiss="modal">ACEPTAR</button>
                        <button type="button" class="btn btn-primary cancelar" data-dismiss="modal">CANCELAR</button>
                    </div>
                    
                </div>
            </div>
          
        </div>
    </div>
</div>








@section Scripts{
    @Scripts.Render("~/Scripts/select2.js")
    <script type="text/javascript">

      
        $(document).ready(function () {

            $(".js-example-basic-multiple").select2({
                placeholder: "Seleccionar Empleado",
                allowClear: true,
            });
            $("#modalMensaje").modal('show');
            $.ajax({
                type: "POST",
                url: "llenar",
                data: "{}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (msg) {
                    listado = msg;

                    $(msg).each(function () {
                        var option = $(document.createElement('option'));

                        option.text(this.Nombre);
                        option.val(this.Codigo);

                        $("#origen").append(option);
                    });
                },
                error: function (msg) {
                    $("#dvAlerta > span").text("Error al llenar el combo");
                }
            });

        });

        $(".js-example-basic-multiple").select2();
    </script>
}